### ISSUE TITLE
Moviepy does not work with Pyinstaller > 5.6.2

### ISSUE THREAD

**Issue by Djdefrag** [pyinstaller/pyinstaller-hooks-contrib#558]
**Good morning, i found out that trying to package a script with moviepy with newer version of Pyinstaller(>5.6.2) leading to an error**
* I think moviepy hook is not working?
* when running

pygame.display.set_mode((854, 480), pygame.NOFRAME)
    pygame.display.set_caption('©2017 CherryByte™ Software')
    pygame.mouse.set_visible(False)
    logo = VideoFileClip('CherryByte Logo.mp4')
    logo.preview()
    pygame.mouse.set_visible(True)
```

PyInstaller command:
```
pyinstall --collect-all moviepy test.py
```

Error:
```
: AttributeError: module 'moviepy.audio.fx.all' has no attribute 'audio_fadein'
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version: 3.10.10
 - Version of `pyinstaller-hooks-contrib`: 2023.0
 - Version of PyInstaller 5.7.0 / 5.8.0 / 5.9.0

**Comment by rokm** [comment]
Can you provide the full error traceback, so we can see the call chain?

Because if the error occurs during import of `moviepy.editor`, `--collect-submodules moviepy.audio.fx --collect-submodules moviepy.video.fx` (or even the brute force `--collect-all moviepy` that you are using) should take care of it (tested with `PyInstaller` 5.9, python 3.10.8, and `moviepy` 1.0.3).

**Comment by rokm** [comment]
If you're using `--windowed` and end up with `NoneType object has no attribute 'write'`, then some part of the code is naively assuming that `sys.stdout` and `sys.stderr` are available. Which, as of [PyInstaller 5.7 is not the case anymore](https://pyinstaller.org/en/v5.7.0/CHANGES.html#incompatible-changes).

So you either need to find and fix the offending code yourself (and preferably report the issue to the package), or add a block like that at the top of your program to add dummy `sys.stdout`/`sys.stderr`:

```python
if sys.stdout is None:
    sys.stdout = open(os.devnull, "w")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w")
```

**Comment by Djdefrag** [comment]
Ahh, so that's why this was happening!

Thank you!!
